// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirectoryContents(arg1) {
  return window['go']['main']['App']['GetDirectoryContents'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SearchWithProgress(arg1) {
  return window['go']['main']['App']['SearchWithProgress'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function ValidateDirectory(arg1) {
  return window['go']['main']['App']['ValidateDirectory'](arg1);
}
