// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelSearch():Promise<void>;

export function ClearSymbolCache():Promise<void>;

export function ExportSearchResults(arg1:Array<main.SearchResult>,arg2:string):Promise<string>;

export function GetAllSymbols(arg1:string,arg2:number):Promise<Array<main.SymbolInfo>>;

export function GetAvailableEditors():Promise<main.EditorAvailability>;

export function GetDirectoryContents(arg1:string):Promise<Array<string>>;

export function GetEditorDetectionStatus():Promise<Record<string, any>>;

export function GetInitialLogs():Promise<Array<main.LogMessage>>;

export function GetKnownTextExtensions():Promise<Array<string>>;

export function GetNewLogs():Promise<Array<main.LogMessage>>;

export function IsAppReady():Promise<boolean>;

export function OpenInDefaultEditor(arg1:string):Promise<void>;

export function OpenInEditorByName(arg1:string,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function ReadFileLog(arg1:string):Promise<string>;

export function ReplaceInFiles(arg1:main.ReplaceRequest):Promise<main.ReplaceResult>;

export function SearchSymbols(arg1:string,arg2:string,arg3:number):Promise<Array<main.SymbolInfo>>;

export function SearchWithProgress(arg1:main.SearchRequest):Promise<Array<main.SearchResult>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function ShowInFolder(arg1:string):Promise<void>;

export function ValidateDirectory(arg1:string):Promise<boolean>;
