// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExportResults(arg1:main.ExportRequest):Promise<string>;

export function ExportResultsWithSaveDialog(arg1:Array<main.SearchResult>,arg2:main.ExportFormat):Promise<string>;

export function GetDirectoryContents(arg1:string):Promise<Array<string>>;

export function SearchCode(arg1:main.SearchRequest):Promise<Array<main.SearchResult>>;

export function SearchWithProgress(arg1:main.SearchRequest):Promise<Array<main.SearchResult>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function ShowInFolder(arg1:string):Promise<void>;

export function ValidateDirectory(arg1:string):Promise<boolean>;
