// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelSearch() {
  return window['go']['main']['App']['CancelSearch']();
}

export function ClearSymbolCache() {
  return window['go']['main']['App']['ClearSymbolCache']();
}

export function ExportSearchResults(arg1, arg2) {
  return window['go']['main']['App']['ExportSearchResults'](arg1, arg2);
}

export function GetAllSymbols(arg1, arg2) {
  return window['go']['main']['App']['GetAllSymbols'](arg1, arg2);
}

export function GetAvailableEditors() {
  return window['go']['main']['App']['GetAvailableEditors']();
}

export function GetDirectoryContents(arg1) {
  return window['go']['main']['App']['GetDirectoryContents'](arg1);
}

export function GetEditorDetectionStatus() {
  return window['go']['main']['App']['GetEditorDetectionStatus']();
}

export function GetInitialLogs() {
  return window['go']['main']['App']['GetInitialLogs']();
}

export function GetKnownTextExtensions() {
  return window['go']['main']['App']['GetKnownTextExtensions']();
}

export function GetNewLogs() {
  return window['go']['main']['App']['GetNewLogs']();
}

export function IsAppReady() {
  return window['go']['main']['App']['IsAppReady']();
}

export function OpenInDefaultEditor(arg1) {
  return window['go']['main']['App']['OpenInDefaultEditor'](arg1);
}

export function OpenInEditorByName(arg1, arg2) {
  return window['go']['main']['App']['OpenInEditorByName'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function ReadFileLog(arg1) {
  return window['go']['main']['App']['ReadFileLog'](arg1);
}

export function SearchSymbols(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchSymbols'](arg1, arg2, arg3);
}

export function SearchWithProgress(arg1) {
  return window['go']['main']['App']['SearchWithProgress'](arg1);
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function ShowInFolder(arg1) {
  return window['go']['main']['App']['ShowInFolder'](arg1);
}

export function ValidateDirectory(arg1) {
  return window['go']['main']['App']['ValidateDirectory'](arg1);
}
